config/routes.rb
IrctcAlert::Application.routes.draw do
  resources :public_holidays

  resources :user_details

end

app/models/public_holiday.rb
class PublicHoliday < ActiveRecord::Base
  attr_accessible :name, :leave_date
end

app/models/sms_sender.rb
require "net/http"
class SmsSender
def initialize(user_phone, password, provider = "fullonsms")
@sender = user_phone
@password = password
@provider = provider
end

def send(recipient,message)
uri = URI("http://ubaid.tk/sms/sms.aspx")
params = { uid: @sender,
pwd: @password,
phone: recipient,
msg: message,
provider: @provider
}
uri.query = URI.encode_www_form(params)
response = Net::HTTP.get_response(uri)
if response.is_a?(Net::HTTPSuccess) && response.body == "1"
puts "Message Sent"
else
puts "Something Went Wrong. Error Code = #{response.body}"
end
end
end

#sample usage

fullonsms = SmsSender.new(9894555817,"57829")
fullonsms.send("PHONE","MSG")

app/models/user_detail.rb
class UserDetail < ActiveRecord::Base
  attr_accessible :name, :phone_number, :email_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/public_holidays_controller.rb
class PublicHolidaysController < ApplicationController
  # GET /public_holidays
  # GET /public_holidays.json
  def index
    @public_holidays = PublicHoliday.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @public_holidays }
    end
  end

  # GET /public_holidays/1
  # GET /public_holidays/1.json
  def show
    @public_holiday = PublicHoliday.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @public_holiday }
    end
  end

  # GET /public_holidays/new
  # GET /public_holidays/new.json
  def new
    @public_holiday = PublicHoliday.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @public_holiday }
    end
  end

  # GET /public_holidays/1/edit
  def edit
    @public_holiday = PublicHoliday.find(params[:id])
  end

  # POST /public_holidays
  # POST /public_holidays.json
  def create
    @public_holiday = PublicHoliday.new(params[:public_holiday])

    respond_to do |format|
      if @public_holiday.save
        format.html { redirect_to @public_holiday, notice: 'Public holiday was successfully created.' }
        format.json { render json: @public_holiday, status: :created, location: @public_holiday }
      else
        format.html { render action: "new" }
        format.json { render json: @public_holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /public_holidays/1
  # PUT /public_holidays/1.json
  def update
    @public_holiday = PublicHoliday.find(params[:id])

    respond_to do |format|
      if @public_holiday.update_attributes(params[:public_holiday])
        format.html { redirect_to @public_holiday, notice: 'Public holiday was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @public_holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /public_holidays/1
  # DELETE /public_holidays/1.json
  def destroy
    @public_holiday = PublicHoliday.find(params[:id])
    @public_holiday.destroy

    respond_to do |format|
      format.html { redirect_to public_holidays_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController
  # GET /user_details
  # GET /user_details.json
  def index
    @user_details = UserDetail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_details }
    end
  end

  # GET /user_details/1
  # GET /user_details/1.json
  def show
    @user_detail = UserDetail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_detail }
    end
  end

  # GET /user_details/new
  # GET /user_details/new.json
  def new
    @user_detail = UserDetail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_detail }
    end
  end

  # GET /user_details/1/edit
  def edit
    @user_detail = UserDetail.find(params[:id])
  end

  # POST /user_details
  # POST /user_details.json
  def create
    @user_detail = UserDetail.new(params[:user_detail])

    respond_to do |format|
      if @user_detail.save
        format.html { redirect_to @user_detail, notice: 'User detail was successfully created.' }
        format.json { render json: @user_detail, status: :created, location: @user_detail }
      else
        format.html { render action: "new" }
        format.json { render json: @user_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_details/1
  # PUT /user_details/1.json
  def update
    @user_detail = UserDetail.find(params[:id])

    respond_to do |format|
      if @user_detail.update_attributes(params[:user_detail])
        format.html { redirect_to @user_detail, notice: 'User detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_details/1
  # DELETE /user_details/1.json
  def destroy
    @user_detail = UserDetail.find(params[:id])
    @user_detail.destroy

    respond_to do |format|
      format.html { redirect_to user_details_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_holidays_helper.rb
module PublicHolidaysHelper
end

app/helpers/user_details_helper.rb
module UserDetailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IrctcAlert</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/public_holidays/_form.html.erb
<%= form_for(@public_holiday) do |f| %>
  <% if @public_holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@public_holiday.errors.count, "error") %> prohibited this public_holiday from being saved:</h2>

      <ul>
      <% @public_holiday.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>
  <div>
  <%= f.label :leave_date %>
  <%= f.text_field :leave_date, id: 'datepicker'%>
  </div>
  <div class="actions">
    <%= f.submit 'submit', :class=> 'btn btn-primary'%>
  </div>
<% end %>

app/views/public_holidays/edit.html.erb
<div class='container well'>
<div class='row'>
	<div class='span6'>
		<h3>
			IRCTC Reminder Details
		</h3>
	</div>
</div>
</div>
<div class='container well'>
	<h4>Editing public_holiday</h4>

<%= render 'form' %>

<%= link_to 'Show', @public_holiday %> |
<%= link_to 'Back', public_holidays_path %>
</div>

app/views/public_holidays/index.html.erb
<div class='container well'>
<div class='row'>
  <div class='span6'>
    <h3>
      IRCTC Reminder Details
    </h3>
  </div>
</div>
</div>

<div class='well'>
<h4>Listing public_holidays</h4>

<table class = 'table table-bordered table-striped table-hover'>
  <%if @public_holidays.any?%>
  <tr>
    <th>Occasion</th>
    <th>Date</th>
    <th></th>
    <th></th>
  </tr>
<%end%>

<% @public_holidays.each do |public_holiday| %>
  <tr>
    <td><%= public_holiday.name %></td>
    <td><%= public_holiday.leave_date %></td>
    <td><%= link_to 'Edit', edit_public_holiday_path(public_holiday) %></td>
    <td><%= link_to 'Destroy', public_holiday, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
</table>
<%= link_to 'New Public holiday', new_public_holiday_path %>
</div>

app/views/public_holidays/new.html.erb
<div class='container well'>
<div class='row'>
	<div class='span6'>
		<h3>
			IRCTC Reminder Details
		</h3>
	</div>
</div>
</div>

<div class='well'>
<h4>New Public holidays</h4>

<%= render 'form' %>

<%= link_to 'Back', public_holidays_path %>
</div>

app/views/public_holidays/show.html.erb
<div class='container well'>
<div class='row'>
	<div class='span6'>
		<h3>
			IRCTC Reminder Details
		</h3>
	</div>
</div>
</div>
<div class='container well'>
<p id="notice"><%= notice %></p>
<table class = 'table table-bordered table-striped table-hover'>
<tr>
    <th>Occasion</th>
    <th>Date</th>
</tr>
<td><%= @public_holiday.name %></td>
<td><%= @public_holiday.leave_date %></td>
</table>
<%= link_to 'Edit', edit_public_holiday_path(@public_holiday) %> |
<%= link_to 'Back', public_holidays_path %>
</div>

app/views/user_details/_form.html.erb
<%= form_for(@user_detail) do |f| %>
  <% if @user_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_detail.errors.count, "error") %> prohibited this user_detail from being saved:</h2>

      <ul>
      <% @user_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>
  <div>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  </div>
  <div>
  <%= f.label :email_id %>
  <%= f.text_field :email_id %>
  </div>
  <div>
    <%= f.submit 'submit', :class=> 'btn btn-primary'%>
  </div>
<% end %>

app/views/user_details/edit.html.erb
<div class='container well'>
<div class='row'>
	<div class='span6'>
		<h3>
			IRCTC Reminder Details
		</h3>
	</div>
</div>
</div>
<div class='container well'>
<h4>Editing User details</h4>

<%= render 'form' %>

<%= link_to 'Show', @user_detail %> |
<%= link_to 'Back', user_details_path %>
</div>

app/views/user_details/index.html.erb
<div class='container well'>
<div class='row'>
  <div class='span6'>
    <h3>
      IRCTC Reminder Details
    </h3>
  </div>
</div>
</div>

<div class='well'>
<h4>User details</h4>

<table class = 'table table-bordered table-striped table-hover'>
  <%if @user_details.any?%>
  <tr>
    <th>Name</th>
    <th>Phone number</th>
    <th>E-mail id</th>
    <th></th>
    <th></th>
  </tr>
<%end%>
<% @user_details.each do |user_detail| %>
  <tr>
    <td><%= user_detail.name %></td>
    <td><%= user_detail.phone_number %></td>
    <td><%= user_detail.email_id %></td>
    <td><%= link_to 'Edit', edit_user_detail_path(user_detail) %></td>
    <td><%= link_to 'Destroy', user_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User detail', new_user_detail_path %>
</div>

app/views/user_details/new.html.erb
<div class='container well'>
<div class='row'>
	<div class='span6'>
		<h3>
			IRCTC Reminder Details
		</h3>
	</div>
</div>
</div>

<div class='well'>
<h4>New Users</h4>

<%= render 'form' %>

<%= link_to 'Back', user_details_path %>
</div>

app/views/user_details/show.html.erb
<div class='container well'>
<div class='row'>
	<div class='span6'>
		<h3>
			IRCTC Reminder Details
		</h3>
	</div>
</div>
</div>
<div class='container well'>
<p id="notice"><%= notice %></p>

<table class = 'table table-bordered table-striped table-hover'>
<tr>
    <th>Name</th>
    <th>Phone number</th>
    <th>E-mail id</th>
</tr>
	<td><%= @user_detail.name %></td>
	<td><%= @user_detail.email_id %></td>
	<td><%= @user_detail.phone_number %></td>
</table>

<%= link_to 'Edit', edit_user_detail_path(@user_detail) %> |
<%= link_to 'Back', user_details_path %>
</div>